# Generated by Django 5.0.1 on 2024-01-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Manager", "Manager"),
                    ("Admin", "Admin"),
                    ("Other", "Other"),
                    ("None", None),
                ],
                default="Admin",
                max_length=200,
                null=True,
            ),
        ),
    ]
